import { Player, Team } from "@/lib/definitons";

export const teams: Team[] = [
  {
    id: 1,
    name: "Lions United",
    logo_url: "https://example.com/logos/lions_united.png",
    founded_year: 1990,
    description: "A formidable team known for their aggressive play style.",
  },
  {
    id: 2,
    name: "Eagle Eyes",
    logo_url: "https://example.com/logos/eagle_eyes.png",
    founded_year: 1985,
    description: "Renowned for their precise and strategic gameplay.",
  },
  {
    id: 3,
    name: "Warrior Kings",
    logo_url: "https://example.com/logos/warrior_kings.png",
    founded_year: 2000,
    description: "A young team with a lot of potential and spirit.",
  },
  {
    id: 4,
    name: "Thunderbolts",
    logo_url: "https://example.com/logos/thunderbolts.png",
    founded_year: 1975,
    description: "Veteran team with a history of championship titles.",
  },
  {
    id: 5,
    name: "Dragon Slayers",
    logo_url: "https://example.com/logos/dragon_slayers.png",
    founded_year: 1995,
    description: "Known for their fierce competitiveness and teamwork.",
  },
];

export const players: Player[] = [
  {
    id: 1,
    first_name: "John",
    last_name: "Doe",
    date_of_birth: new Date('1990-01-01'),
    batting_style: 'Right-hand',
    bowling_style: 'Right-arm Fast',
    player_role: 'All-rounder',
    jersey_number: 10,
  },
  {
    id: 2,
    first_name: "Don",
    last_name: "Smith",
    date_of_birth: new Date('1992-05-15'),
    batting_style: 'Left-hand',
    bowling_style: 'Left-arm Spin',
    player_role: 'Bowler',
    jersey_number: 22,
  },
  {
    id: 3,
    first_name: "Michael",
    last_name: "Johnson",
    date_of_birth: new Date('1988-07-20'),
    batting_style: 'Right-hand',
    bowling_style: 'Right-arm Medium',
    player_role: 'Batsman',
    jersey_number: 7,
  },
  {
    id: 4,
    first_name: "Chris",
    last_name: "Davis",
    date_of_birth: new Date('1995-03-30'),
    batting_style: 'Left-hand',
    bowling_style: 'No',
    player_role: 'Wicket-keeper',
    jersey_number: 5,
  },
  {
    id: 5,
    first_name: "Chris",
    last_name: "Brown",
    date_of_birth: new Date('1991-11-11'),
    batting_style: 'Right-hand',
    bowling_style: 'Right-arm Spin',
    player_role: 'All-rounder',
    jersey_number: 18,
  },
  {
    id: 6,
    first_name: "David",
    last_name: "Wilson",
    date_of_birth: new Date('1987-09-25'),
    batting_style: 'Right-hand',
    bowling_style: 'Right-arm Fast',
    player_role: 'Bowler',
    jersey_number: 33,
  },
  {
    id: 7,
    first_name: "John",
    last_name: "Taylor",
    date_of_birth: new Date('1993-12-14'),
    batting_style: 'Left-hand',
    bowling_style: 'Left-arm Medium',
    player_role: 'Batsman',
    jersey_number: 12,
  },
  {
    id: 8,
    first_name: "James",
    last_name: "Anderson",
    date_of_birth: new Date('1985-04-10'),
    batting_style: 'Right-hand',
    bowling_style: 'Right-arm Spin',
    player_role: 'All-rounder',
    jersey_number: 21,
  },
  {
    id: 9,
    first_name: "Mathew",
    last_name: "Martin",
    date_of_birth: new Date('1994-07-07'),
    batting_style: 'Left-hand',
    bowling_style: 'Left-arm Fast',
    player_role: 'Bowler',
    jersey_number: 8,
  },
  {
    id: 10,
    first_name: "Robert",
    last_name: "Lee",
    date_of_birth: new Date('1990-02-20'),
    batting_style: 'Right-hand',
    bowling_style: 'Right-arm Medium',
    player_role: 'Wicket-keeper',
    jersey_number: 3,
  },
];