import { Player, Team, TeamPlayer } from "@/lib/definitons";

export const teams: Team[] = [
  {
    team_id: 1,
    name: "Lions United",
    logo_url: "https://example.com/logos/lions_united.png",
    founded_year: 1990,
    description: "A formidable team known for their aggressive play style.",
  },
  {
    team_id: 2,
    name: "Eagle Eyes",
    logo_url: "https://example.com/logos/eagle_eyes.png",
    founded_year: 1985,
    description: "Renowned for their precise and strategic gameplay.",
  },
  {
    team_id: 3,
    name: "Warrior Kings",
    logo_url: "https://example.com/logos/warrior_kings.png",
    founded_year: 2000,
    description: "A young team with a lot of potential and spirit.",
  },
  {
    team_id: 4,
    name: "Thunderbolts",
    logo_url: "https://example.com/logos/thunderbolts.png",
    founded_year: 1975,
    description: "Veteran team with a history of championship titles.",
  },
  {
    team_id: 5,
    name: "Dragon Slayers",
    logo_url: "https://example.com/logos/dragon_slayers.png",
    founded_year: 1995,
    description: "Known for their fierce competitiveness and teamwork.",
  },
];

export const players: Player[] = [
  {
    player_id: 1,
    first_name: "John",
    last_name: "Doe",
    date_of_birth: new Date("1990-01-01"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Fast",
    player_role: "All-rounder",
    jersey_number: 10,
  },
  {
    player_id: 2,
    first_name: "Don",
    last_name: "Smith",
    date_of_birth: new Date("1992-05-15"),
    batting_style: "Left-hand",
    bowling_style: "Left-arm Spin",
    player_role: "Bowler",
    jersey_number: 22,
  },
  {
    player_id: 3,
    first_name: "Michael",
    last_name: "Johnson",
    date_of_birth: new Date("1988-07-20"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Batsman",
    jersey_number: 7,
  },
  {
    player_id: 4,
    first_name: "Chris",
    last_name: "Davis",
    date_of_birth: new Date("1995-03-30"),
    batting_style: "Left-hand",
    bowling_style: "None",
    player_role: "Wicket-keeper",
    jersey_number: 5,
  },
  {
    player_id: 5,
    first_name: "Chris",
    last_name: "Brown",
    date_of_birth: new Date("1991-11-11"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Spin",
    player_role: "All-rounder",
    jersey_number: 18,
  },
  {
    player_id: 6,
    first_name: "David",
    last_name: "Wilson",
    date_of_birth: new Date("1987-09-25"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Fast",
    player_role: "Bowler",
    jersey_number: 33,
  },
  {
    player_id: 7,
    first_name: "John",
    last_name: "Taylor",
    date_of_birth: new Date("1993-12-14"),
    batting_style: "Left-hand",
    bowling_style: "Left-arm Medium",
    player_role: "Batsman",
    jersey_number: 12,
  },
  {
    player_id: 8,
    first_name: "James",
    last_name: "Anderson",
    date_of_birth: new Date("1985-04-10"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Spin",
    player_role: "All-rounder",
    jersey_number: 21,
  },
  {
    player_id: 9,
    first_name: "Mathew",
    last_name: "Martin",
    date_of_birth: new Date("1994-07-07"),
    batting_style: "Left-hand",
    bowling_style: "Left-arm Fast",
    player_role: "Bowler",
    jersey_number: 8,
  },
  {
    player_id: 10,
    first_name: "Robert",
    last_name: "Lee",
    date_of_birth: new Date("1990-02-20"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Wicket-keeper",
    jersey_number: 3,
  },
  {
    player_id: 11,
    first_name: "James",
    last_name: "Anderson",
    date_of_birth: new Date("1992-03-15"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Fast",
    player_role: "Bowler",
    jersey_number: 1,
  },
  {
    player_id: 12,
    first_name: "David",
    last_name: "Warner",
    date_of_birth: new Date("1993-05-20"),
    batting_style: "Left-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Batsman",
    jersey_number: 2,
  },
  {
    player_id: 13,
    first_name: "Kane",
    last_name: "Richardson",
    date_of_birth: new Date("1994-08-12"),
    batting_style: "Right-hand",
    bowling_style: "Left-arm Spin",
    player_role: "All-rounder",
    jersey_number: 4,
  },
  {
    player_id: 14,
    first_name: "Ben",
    last_name: "Stokes",
    date_of_birth: new Date("1991-06-04"),
    batting_style: "Left-hand",
    bowling_style: "Right-arm Fast",
    player_role: "All-rounder",
    jersey_number: 5,
  },
  {
    player_id: 15,
    first_name: "Jos",
    last_name: "Butler",
    date_of_birth: new Date("1990-09-08"),
    batting_style: "Right-hand",
    bowling_style: "None",
    player_role: "Wicket-keeper",
    jersey_number: 6,
  },
  {
    player_id: 16,
    first_name: "Mitchell",
    last_name: "Starc",
    date_of_birth: new Date("1995-01-30"),
    batting_style: "Left-hand",
    bowling_style: "Left-arm Fast",
    player_role: "Bowler",
    jersey_number: 7,
  },
  {
    player_id: 17,
    first_name: "Steve",
    last_name: "Smith",
    date_of_birth: new Date("1989-06-02"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Spin",
    player_role: "Batsman",
    jersey_number: 9,
  },
  {
    player_id: 18,
    first_name: "Trent",
    last_name: "Boult",
    date_of_birth: new Date("1993-07-22"),
    batting_style: "Right-hand",
    bowling_style: "Left-arm Fast",
    player_role: "Bowler",
    jersey_number: 10,
  },
  {
    player_id: 19,
    first_name: "Ross",
    last_name: "Taylor",
    date_of_birth: new Date("1988-03-27"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Batsman",
    jersey_number: 11,
  },
  {
    player_id: 20,
    first_name: "Rashid",
    last_name: "Khan",
    date_of_birth: new Date("1996-09-20"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Spin",
    player_role: "All-rounder",
    jersey_number: 12,
  },
  {
    player_id: 21,
    first_name: "Virat",
    last_name: "Kohli",
    date_of_birth: new Date("1988-11-05"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Batsman",
    jersey_number: 18,
  },
  {
    player_id: 22,
    first_name: "Jasprit",
    last_name: "Bumrah",
    date_of_birth: new Date("1993-12-06"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Fast",
    player_role: "Bowler",
    jersey_number: 93,
  },
  {
    player_id: 23,
    first_name: "Ravindra",
    last_name: "Jadeja",
    date_of_birth: new Date("1988-12-06"),
    batting_style: "Left-hand",
    bowling_style: "Left-arm Spin",
    player_role: "All-rounder",
    jersey_number: 8,
  },
  {
    player_id: 24,
    first_name: "KL",
    last_name: "Rahul",
    date_of_birth: new Date("1992-04-18"),
    batting_style: "Right-hand",
    bowling_style: "None",
    player_role: "Wicket-keeper",
    jersey_number: 1,
  },
  {
    player_id: 25,
    first_name: "Mohammed",
    last_name: "Shami",
    date_of_birth: new Date("1990-09-03"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Fast",
    player_role: "Bowler",
    jersey_number: 11,
  },
  {
    player_id: 26,
    first_name: "Shreyas",
    last_name: "Iyer",
    date_of_birth: new Date("1994-12-06"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Batsman",
    jersey_number: 41,
  },
  {
    player_id: 27,
    first_name: "Washington",
    last_name: "Sundar",
    date_of_birth: new Date("1999-10-05"),
    batting_style: "Left-hand",
    bowling_style: "Right-arm Spin",
    player_role: "All-rounder",
    jersey_number: 5,
  },
  {
    player_id: 28,
    first_name: "Yuzvendra",
    last_name: "Chahal",
    date_of_birth: new Date("1990-07-23"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Spin",
    player_role: "Bowler",
    jersey_number: 3,
  },
  {
    player_id: 29,
    first_name: "Shubman",
    last_name: "Gill",
    date_of_birth: new Date("1999-09-08"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Batsman",
    jersey_number: 77,
  },
  {
    player_id: 30,
    first_name: "Axar",
    last_name: "Patel",
    date_of_birth: new Date("1994-01-20"),
    batting_style: "Left-hand",
    bowling_style: "Left-arm Spin",
    player_role: "All-rounder",
    jersey_number: 20,
  },
  {
    player_id: 31,
    first_name: "Babar",
    last_name: "Azam",
    date_of_birth: new Date("1994-10-15"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Batsman",
    jersey_number: 56,
  },
  {
    player_id: 32,
    first_name: "Shaheen",
    last_name: "Afridi",
    date_of_birth: new Date("2000-04-06"),
    batting_style: "Left-hand",
    bowling_style: "Left-arm Fast",
    player_role: "Bowler",
    jersey_number: 10,
  },
  {
    player_id: 33,
    first_name: "Mohammad",
    last_name: "Rizwan",
    date_of_birth: new Date("1992-06-01"),
    batting_style: "Right-hand",
    bowling_style: "None",
    player_role: "Wicket-keeper",
    jersey_number: 16,
  },
  {
    player_id: 34,
    first_name: "Shadab",
    last_name: "Khan",
    date_of_birth: new Date("1998-10-04"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Spin",
    player_role: "All-rounder",
    jersey_number: 29,
  },
  {
    player_id: 35,
    first_name: "Fakhar",
    last_name: "Zaman",
    date_of_birth: new Date("1990-04-10"),
    batting_style: "Left-hand",
    bowling_style: "Left-arm Medium",
    player_role: "Batsman",
    jersey_number: 39,
  },
  {
    player_id: 36,
    first_name: "Haris",
    last_name: "Rauf",
    date_of_birth: new Date("1993-11-07"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Fast",
    player_role: "Bowler",
    jersey_number: 97,
  },
  {
    player_id: 37,
    first_name: "Naseem",
    last_name: "Shah",
    date_of_birth: new Date("2003-02-15"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Fast",
    player_role: "Bowler",
    jersey_number: 71,
  },
  {
    player_id: 38,
    first_name: "Mohammad",
    last_name: "Nawaz",
    date_of_birth: new Date("1994-03-21"),
    batting_style: "Left-hand",
    bowling_style: "Left-arm Spin",
    player_role: "All-rounder",
    jersey_number: 21,
  },
  {
    player_id: 39,
    first_name: "Shan",
    last_name: "Masood",
    date_of_birth: new Date("1989-10-14"),
    batting_style: "Left-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Batsman",
    jersey_number: 42,
  },
  {
    player_id: 40,
    first_name: "Iftikhar",
    last_name: "Ahmed",
    date_of_birth: new Date("1990-09-03"),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Spin",
    player_role: "All-rounder",
    jersey_number: 23,
  },
  {
    player_id: 41,
    first_name: "Tom",
    last_name: "Latham",
    date_of_birth: new Date('1992-04-02'),
    batting_style: "Left-hand",
    bowling_style: "None",
    player_role: "Wicket-keeper",
    jersey_number: 48,
  },
  {
    player_id: 42,
    first_name: "Devon",
    last_name: "Conway",
    date_of_birth: new Date('1991-07-08'),
    batting_style: "Left-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Batsman",
    jersey_number: 88,
  },
  {
    player_id: 43,
    first_name: "Kyle",
    last_name: "Jamieson",
    date_of_birth: new Date('1994-12-30'),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Fast",
    player_role: "Bowler",
    jersey_number: 32,
  },
  {
    player_id: 44,
    first_name: "Mitchell",
    last_name: "Santner",
    date_of_birth: new Date('1992-02-05'),
    batting_style: "Left-hand",
    bowling_style: "Left-arm Spin",
    player_role: "All-rounder",
    jersey_number: 74,
  },
  {
    player_id: 45,
    first_name: "Glenn",
    last_name: "Phillips",
    date_of_birth: new Date('1996-12-06'),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Spin",
    player_role: "Batsman",
    jersey_number: 23,
  },
  {
    player_id: 46,
    first_name: "Tim",
    last_name: "Southee",
    date_of_birth: new Date('1988-12-11'),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Fast",
    player_role: "Bowler",
    jersey_number: 38,
  },
  {
    player_id: 47,
    first_name: "Daryl",
    last_name: "Mitchell",
    date_of_birth: new Date('1991-05-20'),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Medium",
    player_role: "All-rounder",
    jersey_number: 82,
  },
  {
    player_id: 48,
    first_name: "Lockie",
    last_name: "Ferguson",
    date_of_birth: new Date('1991-06-13'),
    batting_style: "Right-hand",
    bowling_style: "Right-arm Fast",
    player_role: "Bowler",
    jersey_number: 87,
  },
  {
    player_id: 49,
    first_name: "Henry",
    last_name: "Nicholls",
    date_of_birth: new Date('1991-11-15'),
    batting_style: "Left-hand",
    bowling_style: "Right-arm Medium",
    player_role: "Batsman",
    jersey_number: 86,
  },
  {
    player_id: 50,
    first_name: "Michael",
    last_name: "Bracewell",
    date_of_birth: new Date('1991-02-14'),
    batting_style: "Left-hand",
    bowling_style: "Right-arm Spin",
    player_role: "All-rounder",
    jersey_number: 91,
  },
];

export const team_players: TeamPlayer[] = [
  ...(players.slice(0, 12).map(player => ({ team_id: 1, player_id: player.player_id }))),
  ...(players.slice(12, 24).map(player => ({ team_id: 2, player_id: player.player_id }))),
  ...(players.slice(24, 36).map(player => ({ team_id: 3, player_id: player.player_id }))),
  ...(players.slice(36, 48).map(player => ({ team_id: 4, player_id: player.player_id }))),
];

export const tournaments = [
  {
    tournament_id: 1,
    name: "Premier Cricket League 2024",
    start_date: new Date("2024-03-01"),
    end_date: new Date("2024-04-30"),
    format: "T20",
    locations: ["Oval Stadium", "Central Ground", "City Arena"],
    team_ids: [1, 2, 3, 4]
  },
  {
    tournament_id: 2,
    name: "National Cup 2024",
    start_date: new Date("2024-05-15"),
    end_date: new Date("2024-06-15"),
    format: "ODI",
    locations: ["National Stadium", "Sports Complex"],
    team_ids: [1, 2, 3, 4]
  },
  {
    tournament_id: 3,
    name: "Regional Championship",
    start_date: new Date("2024-07-01"),
    end_date: new Date("2024-08-30"),
    format: "Test",
    locations: ["East Ground", "West Park", "North Field"],
    team_ids: [1, 2, 3, 4]
  }
];